# Generated by Django 5.2.8 on 2025-11-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_initial'),
        ('services', '0002_servicecategory_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-scheduled_time']},
        ),
        migrations.AlterModelOptions(
            name='businesshours',
            options={'ordering': ['day_of_week'], 'verbose_name_plural': 'Business Hours'},
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='expertise',
            new_name='specialization',
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='maximum_daily_appointments',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='staff',
            name='services',
            field=models.ManyToManyField(related_name='qualified_staff', to='services.service'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('in_progress', 'In Progress'), ('canceled', 'Canceled'), ('no_show', 'No Show')], default='booked', max_length=20),
        ),
    ]
